### ISSUE TITLE
nanopi-R4S can't reboot

### ISSUE THREAD

**Issue by facboy** [friendlyarm/uboot-rockchip#7]
it seems this still has the voltage problem after warm reboot, the SD card cannot be read.

**Comment by DHDAXCW** [comment]
`--- a/arch/arm64/boot/dts/rockchip/rk3399-nanopi-r4s.dts
+++ b/arch/arm64/boot/dts/rockchip/rk3399-nanopi-r4s.dts
@@ -121,6 +121,11 @@
 	status = "disabled";
 };
 
+&sdmmc {
+	/delete-property/ sd-uhs-sdr104;
+	cap-sd-highspeed;
+};
+
 &u2phy0_host {
 	phy-supply = <&vdd_5v>;
 };`

**Comment by DHDAXCW** [comment]
```
--- a/arch/arm64/boot/dts/rockchip/rk3399-nanopi-r4s.dts
+++ b/arch/arm64/boot/dts/rockchip/rk3399-nanopi-r4s.dts
@@ -121,6 +121,11 @@
 	status = "disabled";
 };
 
+&sdmmc {
+	/delete-property/ sd-uhs-sdr104;
+	cap-sd-highspeed;
+};
+
 &u2phy0_host {
 	phy-supply = <&vdd_5v>;
 };
```

**Comment by DHDAXCW** [comment]
```
--- a/drivers/mmc/core/core.c
+++ b/drivers/mmc/core/core.c
@@ -1371,6 +1371,8 @@ void mmc_power_off(struct mmc_host *host
 
 	mmc_pwrseq_power_off(host);
 
+	mmc_set_initial_signal_voltage(host);
+
 	host->ios.clock = 0;
 	host->ios.vdd = 0;
 
```

**Comment by facboy** [comment]
i was wrong, it works fine.  don't need initial voltage thing.
